import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import './globals.css';
import Provider from './provider';
import {getServerSession} from 'next-auth';
import {authOptions} from './api/auth/[...nextauth]/action';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Citchat App (DEMO)',
  description: 'Chat application generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider session={session}>{children}</Provider>
      </body>
    </html>
  );
}
